config/routes.rb
Rails.application.routes.draw do
	get 'welcome/index'
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

	resources :events
	resources :users, only: [:new, :create]
	resource :user_session, only: [:new, :create, :destroy]

	delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
	get '/sign_in', to: 'user_sessions#new', as: :sign_in

	root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    validates :title, presence: true,
                    length: {minimum: 3, maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
    acts_as_authentic do |c|
        c.crypto_provider = Authlogic::CryptoProviders::Sha512
    end

    # Validate email, and password as you see fit.

    validates :email,
    format: {
        with: /@/,
        message: "should look like an email address."
    },
    length: { maximum: 100 },
    uniqueness: {
        case_sensitive: false,
        if: :will_save_change_to_email?
    }

    validates :password,
    confirmation: { if: :require_password? },
    length: {
        minimum: 8,
        if: :require_password?
    }
    
    validates :password_confirmation,
    length: {
        minimum: 8,
        if: :require_password?
    }
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user_session, :current_user

  private
    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end

    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.user
    end
end

app/controllers/confirm_account_controller.rb
class ConfirmAccountController < ApplicationController
    def new
    end
  
    def create
      @user = User.find_by_email(params[:email])
      if @user
        @user.deliver_password_reset_instructions!
        flash[:success] = "Instructions to reset your password have been emailed to you."
        redirect_to root_path
      else
        flash[:warning] = "No user was found with that email address"
        render :new
      end
    end
  
    def edit
      @user = User.find_by(perishable_token: params[:id])
    end
  
    def update
      @user = User.find_by(perishable_token: params[:id])
      if @user.update_attributes(password_reset_params)
        flash[:success] = "Password successfully updated!"
        redirect_to root_path
      else
        render :edit
      end
    end
  
    private
  
    def password_reset_params
      params.require(:user).permit(:password, :password_confirmation)
    end
  end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    http_basic_authenticate_with name: "user", password: "secret", except: [:index, :show]

    def index
        @events = Event.all
    end

    def show
        @event = Event.find(params[:id])
    end

    def new
        @event = Event.new
    end

    def edit
        @event = Event.find(params[:id])
    end

    def create
        @event = Event.new(event_params)
        
        if @event.save
            redirect_to @event
        else
            render 'new'
        end
    end

    def update
        @event = Event.find(params[:id])
        if @event.update(event_params)
            redirect_to @event
        else
            render 'edit'
        end
    end
    
    def destroy
        @event = Event.find(params[:id])
        @event.destroy

        redirect_to events_path
    end

    private
        def event_params
            params.require(:event).permit(:title, :description, :event_date, :ticket_price, :capacity)
        end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
    def new
    	@user_session = UserSession.new
    end
  
    def create
		@user_session = UserSession.new(user_session_params.to_h)
		if @user_session.save
			redirect_to root_url
		else
			render :action => :new
		end
    end
  
    def destroy
		current_user_session.destroy
		redirect_to new_user_session_url
    end
  
    private
  
    def user_session_params
    	params.require(:user_session).permit(:email, :password, :remember_me)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(users_params)
      if @user.save
        flash[:success] = "Account registered!"
        redirect_to root_path
      else
        render :new
      end
    end
  
    private
  
    def users_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_editform.html.erb
<%= form_with(model: @event, local: true) do |form| %>
 
    <% if @event.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@event.errors.count, "error") %> prohibited
          this event from being saved:
        </h2>
        <ul>
          <% @event.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
   
    <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
      </p>
     
      <p>
        <%= form.label :description %><br>
        <%= form.text_area :description %>
      </p>
  
      <p>
        <%= form.label :event_date %><br>
        <%= form.text_field :event_date %>
      </p>
  
      <p>
        <%= form.label :ticket_price %><br>
        <%= form.text_field :ticket_price %>
      </p>
  
      <p>
        <%= form.label :capacity %><br>
        <%= form.text_field :capacity %>
      </p>
   
    <p>
      <%= form.submit %>
    </p>
   
  <% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>
 
<%= render 'editform' %>
 
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>All Events</h1>

<%= link_to 'New Event', new_event_path %>
<br /> <br />

<table style="width:100%">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Date</th>
    <th>Price</th>
    <th>Capacity</th>
    <th colspan="3">Action</th>
  </tr>
 
  <% @events.each do |event| %>
    <tr style="text-align:center">
      <td><%= event.title %></td>
      <td><%= event.description %></td>
      <td><%= event.event_date %></td>
      <td><%= event.ticket_price %></td>
      <td><%= event.capacity %></td>
      <td><%= link_to 'Show', event_path(event) %></td>
      <td><%= link_to 'Edit', edit_event_path(event) %></td>
      <td><%= link_to 'Destroy', event_path(event),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<br />
<%= link_to 'Back', welcome_index_url %>

app/views/events/new.html.erb
<h1> Create a new event </h1>

<%= render 'editform' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @event.title %>
</p>

<p>
    <strong>Description:</strong>
    <%= @event.description %>
</p>

<p>
    <strong>Date:</strong>
    <%= @event.event_date %>
</p>

<p>
    <strong>Price:</strong>
    <%= @event.ticket_price %>
</p>

<p>
    <strong>Capacity:</strong>
    <%= @event.capacity %>
</p>

<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mission</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h3>Account</h3> 
    <ul>
      <% if current_user %>
          <li><span><%= current_user.email %></span></li>
          <li><%= link_to 'Sign Out', sign_out_path, method: :delete %></li>
      <% else %>
          <li><%= link_to 'Sign In', sign_in_path %></li>
          <li><%= link_to 'Register', new_user_url %></li>
      <% end %>
    </ul>
    <%= yield %>
  </body>
</html>

app/views/user_sessions/new.html.erb
<%= form_for @user_session, url: user_session_url do |f| %>
	<h1>Login</h1>
	
    <% if @user_session.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user_session.errors.count, "error") %> prohibited:</h2>
        <ul>
          <% @user_session.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <%= f.label :email %><br />
    <%= f.text_field :email %><br />
    <br />
    <%= f.label :password %><br />
    <%= f.password_field :password %><br />
    <br />
    <%= f.check_box :remember_me %>
    <%= f.label :remember_me %><br />
    <br />
    <%= link_to 'Back', welcome_index_url %>
    
    <%= f.submit "Login" %>
  <% end %>

app/views/users/new.html.erb
<h1>Register</h1></div>

<%= form_for @user do |f| %>
    
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited:</h2>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <div>
        <%= f.label :email %>
        <%= f.email_field :email%>
    </div>

    <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password%>
    </div>

    <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation%>
    </div>

    <%= link_to 'Back', welcome_index_url %>
    
    <span>
        <%= f.submit 'Register' %>
    </span>

<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to Mission</h1>
<p>Event Management platform</p>

<%= link_to 'All Events', controller: 'events' %>